/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */


	globalArgc = argc;
	globalArgv = argv;


	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE835_Infinite_Loop__while_true_01_good();");
	CWE835_Infinite_Loop__while_true_01_good();

	printLine("Calling CWE835_Infinite_Loop__do_true_01_good();");
	CWE835_Infinite_Loop__do_true_01_good();

	printLine("Calling CWE835_Infinite_Loop__for_01_good();");
	CWE835_Infinite_Loop__for_01_good();

	printLine("Calling CWE835_Infinite_Loop__while_01_good();");
	CWE835_Infinite_Loop__while_01_good();

	printLine("Calling CWE835_Infinite_Loop__for_empty_01_good();");
	CWE835_Infinite_Loop__for_empty_01_good();

	printLine("Calling CWE835_Infinite_Loop__do_01_good();");
	CWE835_Infinite_Loop__do_01_good();

	/* END-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */





#ifdef __cplusplus
	/* Calling C++ good functions */
	/* BEGIN-AUTOGENERATED-CPP-GOOD-FUNCTION-CALLS */

	/* END-AUTOGENERATED-CPP-GOOD-FUNCTION-CALLS */

#endif /* __cplusplus */



	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
	printLine("Calling CWE835_Infinite_Loop__while_true_01_bad();");
	CWE835_Infinite_Loop__while_true_01_bad();

	printLine("Calling CWE835_Infinite_Loop__do_true_01_bad();");
	CWE835_Infinite_Loop__do_true_01_bad();

	printLine("Calling CWE835_Infinite_Loop__for_01_bad();");
	CWE835_Infinite_Loop__for_01_bad();

	printLine("Calling CWE835_Infinite_Loop__while_01_bad();");
	CWE835_Infinite_Loop__while_01_bad();

	printLine("Calling CWE835_Infinite_Loop__for_empty_01_bad();");
	CWE835_Infinite_Loop__for_empty_01_bad();

	printLine("Calling CWE835_Infinite_Loop__do_01_bad();");
	CWE835_Infinite_Loop__do_01_bad();

	/* END-AUTOGENERATED-C-BAD-FUNCTION-CALLS */




	
#ifdef __cplusplus
	/* Calling C++ bad functions */
	/* BEGIN-AUTOGENERATED-CPP-BAD-FUNCTION-CALLS */

	/* END-AUTOGENERATED-CPP-BAD-FUNCTION-CALLS */
	
#endif /* __cplusplus */


	return 0;

} 
